### ISSUE TITLE
Toolbox Not Working!

### ISSUE THREAD

**Issue by tfogarty12** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#1]
Thanks for what looks like a great all in one toolbox.  I am working with Windows / r2018a, with the neural network toolbox installed.   The demo's do not appear to be working for me and I wanted to see if you guys had any suggestions.  I do not have the rrgen features installed, but suspect that only explains the error with the standardized data.  

Please let me know if you need any additional information to help troubleshoot!

 **DemoAnnotatedData**

> Old Demo Folder deleted 
>  
> New OUTPUT folder: "OutputData\ResultsNSR"
> Error on subject nsr001 
> Error on subject nsr004 
> Error on subject nsr009 
> DemoAnnotatedData: TEST FAILED
> Error: analysis not performed

**DemoRawDataICU**

> Old Demo Folder deleted 
> New OUTPUT folder: "OutputData\ResultsICU"
> Error using Main_HRV_Analysis (line 108)
> Error: imput signal or RR interval time series is shorter than the desired
> analysis windows (300 s).
> Error in DemoRawDataICU (line 50)
> [~, resFilename] = Main_HRV_Analysis(signal(:,1),[],'ECGWaveform',...
> Error in run (line 91)
> evalin('caller', strcat(script, ';'));

 

**DemoStandardizedData**

> New OUTPUT folder: "OutputData\ResultsRRgen"
> 'rrgenV3' is not recognized as an internal or external command, 
> operable program or batch file. 
> Array indices must be
> positive integers or logical
> values.
> Error in Main_HRV_Analysis
> (line 107)
>         ||
>         (strcmp(InputFormat,
>         'RRIntervals') &&
>         t(end)/HRVparams.Fs<HRVparams.windowlength)
>         Error in
>         DemoStandardizedData
>         (line 51)
> [results, resFilename] =
> Main_HRV_Analysis(rr,t,'RRIntervals',HRVparams,...
> Error in run (line 91)
> evalin('caller',
> strcat(script, ';'));

**DemoRawDataAF** - generates a nicely labeled ECG strip / SQI. 
 TestAFdata_HRV_results_allwindows_20180630.csv is empty with no results, except for two flag values set to 3.  

> Old Demo Folder deleted 
> New OUTPUT folder: "OutputData\ResultsAFData"
> Creating a new folder: "Annotation", folder is located in C:\01-stp\thirdparty\PhysioNet-Cardiovascular-Signal-Toolbox-master\Demos\OutputData\ResultsAFData\Annotation 
> AF analysis completed for subject TestAFdata 
> HRV Analysis completed for subject ID TestAFdata 
> ** DemoRawDataAF: TEST SUCCEEDED ** 
>  A file named TestAFdata_HRV_results_allwindows_20180630.csv 
>  has been saved in OutputData\ResultsAFData

**Comment by GiuliaDAP** [comment]
Hello,

as you said the error for DemoStandardizedData are due to RRgen.
Regarding the other demos:

- DemoRawDataAF : the demo returns all empty values for HRV metrics because the signal contains Atrial Fibrillation and thus it is not suitable for HRV analysis. 
- DemoRawDataICU : the problem is  Error: input signal or RR interval time series is shorter than the desired analysis windows (300 s).
                                    this error has been corrected on the last version in the main GitHub repo
- DemoAnnotatedData : it is really weird that DemoRawDataAF works but this demo does not since they basically do the same on different data. Please, make sure you are in the Demo subfolder while running the demo.

Let me know if you need anything else.

**Comment by RezaSadeghiWSU** [comment]
Hi Giulia,

Thank you very much for your time and prompt answers. I got following errors when I tried to run the Demos. And is there any way to install rrgenV3 on windows?

Best regards,
Reza Sadeghi

**DemoStandardizedData.m**

*** Error!***
For input type "RRIntervals" must provide 
vetcor with time indices of the rr interval data 
***HRV analyis will be perfomed!***

Dot indexing is not supported for variables of this type.

Error in DemoStandardizedData (line 59)
currentFile = [HRVparams.writedata filesep resFilename.HRV '.csv'];

**DemoRawDataICU.m**

Creating a new folder: "Annotation", folder is located in C:\Users\Reza Sadeghi\Documents\Sleep study_Strategy 2\Programming\PhysioNet-Cardiovascular-Signal-Toolbox\PhysioNet-Cardiovascular-Signal-Toolbox-master\Demos\OutputData\ResultsICU\Annotation 

*** Warning!***
The signal is shorter than the analysis window length 
***HRV analyis can fail!***

AF analysis completed for subject TestICUdata 
Analyizing PPG 
Analyizing ABP 
HRV Analysis completed for subject ID TestICUdata 
Error using fread
Invalid file identifier. Use fopen to generate a valid file identifier.

Error in read_ann (line 54)
A= fread(fid, [2, inf], 'uint8')';

Error in DemoRawDataICU (line 61)
ppg_ann = read_ann(AnnFile,'ppg');

**DemoPVC.m**

Adding the PhysioNet Cardiovascular Signal Toolbox to Matlab path
PhysioNet Cardiovascular Signal Toolbox successfully added to Matlab path
QRS detect ...
Elapsed time is 2.512434 seconds.
Feature extraction ...
Starting parallel pool (parpool) using the 'local' profile ...
connected to 2 workers.
Elapsed time is 44.387569 seconds.
Classification ...
Elapsed time is 0.984788 seconds.

 ** Demo PVC: TEST FAILED ** 
Error: generated output does not match reference 

**DemoMultiScaleEntropy.m**
Adding the PhysioNet Cardiovascular Signal Toolbox to Matlab path
PhysioNet Cardiovascular Signal Toolbox successfully added to Matlab path
'rrgenV3' is not recognized as an internal or external command, 
operable program or batch file. 
Index exceeds the number of array elements (0).

Error in FindSpikesInRR (line 43)
FiveRR_MedianVal = [RR(1:5) FiveRR_MedianVal(3:end-3)];

Error in RRIntervalPreprocess (line 141)
idxRRtoBeRemoved = FindSpikesInRR(rr, perLimit);

Error in DemoMultiScaleEntropy (line 47)
[NN, tNN, fbeats] = RRIntervalPreprocess(rr,t,[], HRVparams);
 
IdleTimeout has been reached.
Parallel pool using the 'local' profile is shutting down.

**Comment by RezaSadeghiWSU** [comment]
Directory of "\PhysioNet-Cardiovascular-Signal-Toolbox-master\Tools\ECG_Analysis_Tools\VF Detection" contains libsvm-3.11. But we need 3.20 in "\PhysioNet-Cardiovascular-Signal-Toolbox master\Tools\ECG_Analysis_Tools\AF Detection". It is accessible via "https://www.softpedia.com/get/Programming/Components-Libraries/LIBSVM.shtml".

Regards,
Reza

**Comment by GiuliaDAP** [comment]
For AF detection it is NOT NECESSARY to upgrade to lbsvm-3.20. In your previous comment the demo ICU completed AF detection successfully.
From what I can see the problem is in the file reading, so I suspect the demo are not called inside the Demo directory. 
For the RRgen tool please fallow the instruction in the readme.

**Comment by RezaSadeghiWSU** [comment]
After doing analysis over some data I get some annotations. And the following error:
Basic HRV Analysis faild for subject: 0000,  
What does it mean?
