### ISSUE TITLE
draw_dtw.m use "dist" function that does not exist in MATLAB core

### ISSUE THREAD

**Issue by embar-** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#12]
PhysioNet-Cardiovascular-Signal-Toolbox-master/Tools/PPG_Tools/draw_dtw.m at line 76 use "dist" function that does not exist in MATLAB core. Please replace it with some equivalent or create it as some subfunction. 

```
Warning: MATLAB:UndefinedFunction

Undefined function 'dist' for input arguments of type 'double'.

> draw_dtw:76
> PPG_SQI_buf:145
> calculate_ppgsqi:64

 Analyze_ABP_PPG_Waveforms
```

**Comment by GiuliaDAP** [comment]
_dist_ is a Matlab function (https://www.mathworks.com/help/deeplearning/ref/dist.html). 

Please, make sure to use the correct Matlab version (Matlab 2017b (v9.3) ) as reported in the README file along with all the required toolboxes listed (required Matlab Toolboxes: Signal Processing Toolbox, and Statistics and Machine Learning Toolbox, Neural Network Toolbox).
