### ISSUE TITLE
Demo Failed Matlab R2019a

### ISSUE THREAD

**Issue by jonesnp323** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#19]
Hello, Thanks for making this toolbox. I am having trouble with the getting DemoAnnotatedData.m to run successfully. In particular, there seems to be a scientific notation error when writing to .csv.  In the AllPatients_HRV_results_allwindows...csv file Variable NNvariance is off by x10^3; for example  subject nsr001 NNvariance in NRS_HRV...csv file is 3.2344 and for the actual output on my cpu it is 3234.3955. In addition, SD1SD2 is off by x10^3. In addition the ApEn variable values are off by no detectable metric. Assistant is sorting this out would be much appreciated.

Thanks
~Neil

**Comment by GiuliaDAP** [comment]
Hi, what version are you using?

Just cloned the master branch and DemoAnnotatedData.m ann couldn't replicate your issue, it worked fine.

Note that over the last year several changes have been made to fix SD1SD2 (commit  2936de1  on 8 Aug 2018), NNvariance (commit 36ab3f5 on 16 Feb 2019) and ApEn ( commit 639afd3 on 16 Jul 2019) values and the demo reference files have been updated accordingly.

You are probably using an updated version of the tools with an old version of the demo. 

Hope this help.

Giulia

**Comment by jonesnp323** [comment]
Hi, I am using the latest version. I just deleted the toolkit and downloaded the cloned the repository using git clone and ran the DemoAnnatedData funtion and I get the same error and when I look in the files its those variables that are different. Can you tell me what the NNvariance value is supposed to be for the nsr001 t_start 0. I am getting 3234.3955. 

Thanks,
Neil

**Comment by GiuliaDAP** [comment]
The correct value is 3.2344 (as in [NSR_HRV_allwindows_allpatients.csv]( https://github.com/cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox/blob/master/Demos/ReferenceOutput/NSR_HRV_allwindows_allpatients.csv)).

If you are gettin 3232.3955 I suspect you have an older version of the toolbox functions somwhere on your PC.

**Comment by jonesnp323** [comment]
That is not likely to be the case this is on my unix server and I have deleted the only copy of the toolbox and replaced it completely and manually added it to my path. When I check the path EvalTimeDomainHRVstats.m I get only one location. Any other possibilities? This is what my code to calculate NNvariable reads:
  out.NNvariance(i_win) = var(nn_win.* 1000); % compute and convert to ms^2

**Comment by GiuliaDAP** [comment]
Sorry, there has been an issue with the demo reference file updating - the correct value for NN is 3232.3955.
All the demo files need to be updated. I'm working on that. They should be available in the next hour or so. 

Thanks for pointing this out.

**Comment by GiuliaDAP** [comment]
Please, let me know if the demos are now working.
Thanks again.
Giulia
