### ISSUE TITLE
Dicrotic notch & Diastolic peak 

### ISSUE THREAD

**Issue by Baratheon174** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#2]
Hello! 

Thank you for your excellent work. It is really helpful. When I was using it to extract PPG signal features, I found some questions. I can't find any functions about detecting the Systolic peak, Dicrotic notch and Diastolic peak of PPG signal.   In folder named "PPG_Tools", I only found mentions to detect Peaks. 

If I miss them, please tell me where they are and how to use them. 
If not, do you brilliant guys have some suggestions or  reference code？ Thanks a lot ^_^

**Comment by GiuliaDAP** [comment]
Hello,

The toolbox does not provide Systolic peak, Dicrotic notch and Diastolic peak detection algorithm.
You can use the qppg.m function to detect the onset position of PPG beats:

 ppgOnsets = qppg(data,fs,from,to)

Once onset detection is performed, the PPG_SQI_buf function to analyze the signal quality of each PPG beat.

Hope this help.

**Comment by lzduser** [comment]
Hello!
Thanks for sharing the toolbox. An error occur (error:Undefined function or variable 'dpcore' ) when I was using the PPG_SQL_buf.m function, and I can't find dpcore.m funciton in folder "PPG_Tools". Did I lose this document?
I use demo sampledata named "ppgsampledata" to test PPG_SQI_buf.m function with windows/ Matlab R2017a:

load('ppgsampledata.mat');
fs = 125;
annt = qppg(data_simp, fs, 1, length(data_simp));
[annot,sqimatrix,template,valid] = PPG_SQI_buf(data_simp, annt);

**Comment by Baratheon174** [comment]
Hi @lzduser , 
I tested this function by your code. But there is not any error or warning. I don't know why.

 I guess that maybe you didn't download  all of required Matlab Toolboxes (Signal Processing Toolbox, and Statistics and Machine Learning Toolbox, Neural Network Toolbox). By the way, I tested this function with windows/MatlabR2018a. 

I hope this may help you.

> Hello!
> Thanks for sharing the toolbox. An error occur (error:Undefined function or variable 'dpcore' ) when I was using the PPG_SQL_buf.m function, and I can't find dpcore.m funciton in folder "PPG_Tools". Did I lose this document?
> I use demo sampledata named "ppgsampledata" to test PPG_SQI_buf.m function with windows/ Matlab R2017a:
> 
> load('ppgsampledata.mat');
> fs = 125;
> annt = qppg(data_simp, fs, 1, length(data_simp));
> [annot,sqimatrix,template,valid] = PPG_SQI_buf(data_simp, annt);

**Comment by lzduser** [comment]
Thanks for your reply @Baratheon174 . I only found dpcore.m in folder mex_dpcore, it seems that I need to run this file with C++ complier. Is the decore.m built-in function in your MATLAB version?

**Comment by lzduser** [comment]
Thanks for you reply @Baratheon174 . I ignored the  decore.mexw64 file.

**Comment by GiuliaDAP** [comment]
Hi @lzduser, hope you are now able to use the PPG_SQI_buf code.
To avoid future issues with the mex code I introduced an option that automatically switches to the Matlab dp_dwt when dpfast is not working.
The reason to use dpfast is to speed up the code when evaluating large files (i.e., 1 day of PPG or more).
Giulia
