### ISSUE TITLE
Appending to an existing csv file with different column number

### ISSUE THREAD

**Issue by andrejsf** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#21]
Was trying to understand why it fails to work until I found another output file with the same name in MATLAB path with different output columns. Then SaveHRVoutput can't concatenate two tables. (This can happen if you worked in one directory and then switched current folder to another).
Also, not clear, why it should append to the same file by default and not overwrite it.

In general it is a very cool and advanced toolbox, but it lacks a bit of debugging markers. It can fail quietly with a vague explanation in AnalysisError.txt. At least could ooutput there an original debugger message and stack.

Thanks

**Comment by gariclifford** [comment]
I'm sorry - your comment is very vague itself, and doesn't help us work out what you are finding doesn't work as you expect it to work. Please explain clearly what you expect to happen and what does happen, and perhaps we can work out if it's just a misunderstanding, a 'feature', or a desire for a feature that doesn't exist. Just to note, this toolbox is intended for researchers willing to dig into the code, and generate scientifically repeatable results in a scalable manner. There was never an intention to create to a one-click solution to HRV analysis. This always leads to mistakes, and sloppy work.
