### ISSUE TITLE
missing function PreparDataForHRVAnlysis 

### ISSUE THREAD

**Issue by P-Beach** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#23]
Hi, 

Trying to use the physionet toolbox for the first time and when running through code on a line-by-line basis to get HRV (which wasn't working using the normal InitializeHRVparams -> Main_HRV_Analysis) I found that matlab was giving me this error when trying to do the pre-processing steps:

>> [NN, tNN, tWin, AFWindows,out] = PreparDataForHRVAnlysis(rr,t,[],sqi,HRVparams,subID);
Undefined function or variable 'PreparDataForHRVAnlysis'.

I am utilizing MATLAB_2019a on a MacOS Mojave system. Physionet CV toolbox v 1.0.2

Searching in the directory for the toolbox I'm not finding this function there. It doesn't show up after removing/re-downloading the toolbox from the GitHub source.

Does anyone have this function available or have other thoughts?

Thanks!

**Comment by giyilmaz** [comment]
Hi, 

I am also first time using  the toolbox and when I run through "Main_HRV_Analysis" code line by line  I get the error : 
[NN, tNN, tWin, AFWindows,out] = PreparDataForHRVAnlysis(rr,t,[],sqi,HRVparams,subID);
Undefined function or variable 'PreparDataForHRVAnlysis'.

Therefore I couldn't locate the function  'PreparDataForHRVAnlysis' inside the folders. 

Does anyone have this function available or have other recommendations?

Thanks!

**Comment by GiuliaDAP** [comment]
Hello,
the function you are looking for is a subfunction within the Main_HRV_Analysis.m file starting at line 292 
https://github.com/cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox/blob/4d69d10c27ca1a63823d1bc7015c3238fb9c3fbc/Main_HRV_Analysis.m#L292

```
function [NN, tNN, tWin,AFWindows,out] = PreparDataForHRVAnlysis(rr,t,annotations,sqi,HRVparams,subjectID)

    out = []; % Struct used to save DFA and MSE preprocessed data
 
    % Exclude undesiderable data from RR series (i.e., arrhytmia, low SQI, ectopy, artefact, noise)
    [NN, tNN] = RRIntervalPreprocess(rr,t,annotations, HRVparams);  
    tWin = CreateWindowRRintervals(tNN, NN, HRVparams);    % Create Windows for Time and Frequency domain 
    
    % Create Windows for MSE and DFA and preprocess
    if HRVparams.MSE.on || HRVparams.DFA.on
       % Additional pre-processing to deal with missing data for MSE and DFA analysis     
       [out.NN_gapFilled, out.tNN_gapFilled] = RR_Preprocessing_for_MSE_DFA( NN, tNN );
    end
    if HRVparams.MSE.on
       out.tWinMSE = CreateWindowRRintervals(out.tNN_gapFilled, out.NN_gapFilled, HRVparams,'mse');
    end
    if HRVparams.DFA.on
        out.tWinDFA = CreateWindowRRintervals(out.tNN_gapFilled, out.NN_gapFilled, HRVparams,'dfa');
    end    
    
    % 2. Atrial Fibrillation Detection
    if HRVparams.af.on 
        [AFtest, AfAnalysisWindows] = PerformAFdetection(subjectID,t,rr,sqi,HRVparams);
        fprintf('AF analysis completed for subject %s \n', subjectID);
        % Remove RRAnalysisWindows contating AF segments
        [tWin, AFWindows]= RemoveAFsegments(tWin,AfAnalysisWindows, AFtest,HRVparams);
        if HRVparams.MSE.on
            out.tWinMSE = RemoveAFsegments(out.tWinMSE,AfAnalysisWindows, AFtest,HRVparams);
        end
        if HRVparams.DFA.on 
            out.tWinDFA = RemoveAFsegments(out.tWinDFA,AfAnalysisWindows, AFtest,HRVparams);
        end
    else
        AFWindows = [];
    end
    
end
```
