### ISSUE TITLE
'readHeader' error

### ISSUE THREAD

**Issue by kablanyavuz** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#24]
Unrecognized function or variable 'readheader'.

Error in Basic_Demo (line 40)
sigInfo = readheader([InputFolder filesep SigName '.hea']);

**Comment by GiuliaDAP** [comment]
Did you follow the instructions and run: run startup.m to install the software? It is not possible to use the toolbox or run a demo otherwise.

**Comment by kablanyavuz** [comment]
We have solved the problem. Thanks for your help. 




Android için Outlook'u edinin







On Thu, Mar 26, 2020 at 4:06 PM +0300, "Giulia Da Poian" <notifications@github.com> wrote:















Did you follow the instructions and run: run startup.m to install the software? It is not possible to use the toolbox or run a demo otherwise.



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.






*** Bu e-posta mesaji kisiye ozel olup, gizli bilgiler iceriyor olabilir. Eger bu e-posta mesaji size yanlislikla ulasmissa, icerigini hicbir sekilde kullanmayiniz ve ekli dosyalari acmayiniz. Bu durumda lutfen e-posta mesajini gonderen kullaniciya haber veriniz ve t�m elektronik ve yazili kopyalarini siliniz. Karadeniz Teknik Universitesi bu e-posta mesajinin i�eriii ile ilgili olarak hicbir hukuksal sorumlulugu kabul etmez. ***
*** This e-mail message is private and may contain confidential information. If this e-mail message has been received by mistake, do not use the contents in any way and do not open attached files. In this case, please notify the user who sent the e-mail message and delete all electronic and printed copies. Karadeniz Technical University does not accept any legal responsibility for the content of this e-mail message. ***
