### ISSUE TITLE
RemoveAFsegments.m is not removing the right segments!

### ISSUE THREAD

**Issue by mariajribeiro** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#31]
In RemoveAFsegments.m the script tries to identify the segments of RR data that contain the AFs, however it is not taking into consideration the length of the segments used to identify the AFs and therefore is misidentifying the segments.

I propose the following change in the function using beginning and end of window assuming windows are not overlapping - maybe it would be a good idea to not ask for window increment in AF detection (in InitializeHRVparams.m)  - just assume no overlapping windows:

function [cleanRRAnalysisWindows,idx_af] = RemoveAFsegments(RRAnalysisWindows,AfAnalysisWindows, AFtest, HRVparams)

cleanRRAnalysisWindows = RRAnalysisWindows;

% Exclude AF Segments
% afsegs = AfAnalysisWindows(AFtest == 1); % afsegs is in seconds
afsegs_int = AfAnalysisWindows(AFtest == 1);  % 
afsegs_end = AfAnalysisWindows(find(AFtest == 1) + 1);
idx_af = [];

if ~isempty(afsegs_int)
    for k = 1:length(afsegs_int)
        try
            idx_af = [idx_af find(RRAnalysisWindows <= afsegs_int(k) & HRVparams.windowlength + RRAnalysisWindows > afsegs_end(k))];
        catch
        end
    end
    idx_af = unique (idx_af); % Do not consider duplicate positions
    cleanRRAnalysisWindows(idx_af) = NaN;  % Remove all the windows with AF   
end

**Comment by mariajribeiro** [comment]
Bother. My solution still does not solve the problem! let me work on it a bit more.

**Comment by GiuliaDAP** [comment]
@mariajribeiro thanks for pointing this out. Please, can you also provide a concrete example?

If you indeed find a bug, do not post the code here but create a new branch for solving this issue and then submit a pull request.

@perezald do you have time to look into this  is case it turns out to be a real bug?

**Comment by mariajribeiro** [comment]
It is working - false alarm! Sorry.
