### ISSUE TITLE
Testing with MIMIC-III ECG Waveform Data

### ISSUE THREAD

**Issue by waqaraziz123** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#4]
Hi,

Thank you for this wonderful toolbox. I am trying to calculate HRV for MIMIC ECG signals and need to ask  that is this toolbox being tested for subject dataset (Fs=125Hz) ?

Thanks

**Comment by gariclifford** [comment]
I'm not sure if you ever managed to read the MIMIC II data, but as we describe in the accompanying paper, this toolbox is not designed to support I/O libraries. Only native Matlab file formats are supported (by Mathworks) ... Matlab file version v4 is WFDB-compliant, so it looks like we support WFDB - but we don't. Reading your data in the right format (scaling and adding appropriate offsets), is the responsibility of the user. We provide a couple of examples to get you going, but there isn't enough time left on Earth to support every file format. To read files on Physionet, please refer to physionet.org for information on that. (WFDB is a family of libraries and there can be many versions.)
