### ISSUE TITLE
No link to Phys Meas paper in README

### ISSUE THREAD

**Issue by erikr** [cliffordlab/PhysioNet-Cardiovascular-Signal-Toolbox#6]
I recommend linking to the Phys Meas paper in the README:

http://iopscience.iop.org/article/10.1088/1361-6579/aae021/pdf

**Comment by gariclifford** [comment]
Only if it’s open – otherwise I prefer my version in the code so it’s self-contained.


---
Gari. D. Clifford,  DPhil
[ https://alum.mit.edu/www/gari ]

**Comment by erikr** [comment]
@GiuliaDAP added the reference with DOI to the README which solves the underlying issue here; the user would like to easily identify the accompanying paper.
